### ISSUE TITLE
strip_tags removes tags and does not put in a space

### ISSUE THREAD

**Issue by sn-devdev** [beniwohli/django-cms-search#5]
In search_indexes.py on lines 51 and 53, strip tags is used. strip_tags removes all tags with nothing, when indexing text plugins with <br/> in it (can happen pretty often), the last word of the line will be concatenated with the first word on the next line. This generates wrong indexing files (experienced this with haystack an whoosh). 

this is my solution

import re

def custom_strip_tags(value):
    """Returns the given HTML with all tags stripped."""
    return re.sub(r'<[^>]*?>', ' ', force_unicode(value))

then replace the two instances of strip_tags with the custom one. 

Best!

**Comment by beniwohli** [comment]
Good catch, thank you. But I don't really like the combination of regexes with HTML anyway, so what about this?

```
from BeautifulSoup import BeautifulSoup

' '.join(BeautifulSoup(value).findAll(text=True))
```

Of course, that would introduce a new dependency...

**Comment by sn-devdev** [comment]
For me BeautifulSoup is very fine, i use it in many places. Up to you, I just think it is important to fix the issue, i really was wondering, why the heck it did not find a given word ;)

**Comment by kezabelle** [comment]
I noticed this same problem, so it's good to see a ticket already raised for it.

Personally, I'd be -1 for adding BeautifulSoup as a dependency, especially when the regex solution is, for better or worse, exactly what [django does](https://code.djangoproject.com/browser/django/trunk/django/utils/html.py#L83).

**Comment by stefanfoulis** [comment]
unfortunately this still leaves leaves the contents of `<script>`-tags in the document.
Since it's rather bad practice to use regexes on html and beatifulsoup gives us everything that is needed, I propose this implementation:

```
def strip_all_tags(text):
    soup = BeautifulSoup(text.lower())
    # we completely remove script tags
    to_extract = soup.findAll('script')
    for item in to_extract:
        item.extract()
    return unicode(soup.text)
```

**Comment by ghost** [comment]
I don't know, because all I did was to "pimp" the standard strip_tags which lives in standard Django which is used all over the place on any html flying around to fit the special here. IMHO if you just introduce beautifulsoup (which I use all the time and like very much) dependency for this two tasks which should work perfectly well with regexes, maybe it's a bit like shooting canonballs on little birds.

 Just my 2 cents. 

(just for your info, sn-devdev is now sn_e5)
