### ISSUE TITLE
AttributeError in cms_search_tags.py

### ISSUE THREAD

**Issue by sn-devdev** [beniwohli/django-cms-search#7]
I just experienced something weird which I don't really understand what might be the cause. 

On a new live site, while searching for a given term (here it was "Produkte", which should definitely give some results on the respective page), it produced this error: 

 File "/var/www/domains/******/project/cms_search/search_helpers/templatetags/cms_search_tags.py", line 48, in get_value
    untranslated = getattr(obj, field_name)

AttributeError: 'NoneType' object has no attribute 'url'

Everything else seemed to work very fine. It might very well be that there is something i did wrong in my models that are searchable as well and that this issue has nothing really to do with cms-search itself. I am using haystack with whoosh.

However, this is my hotfix, I think it might be helpful and does not do any damage to the rest of the system:

(cms_search_tags.py line 48 onward)

```
    untranslated = ""
    try:
        untranslated = getattr(obj, field_name)
    except AttributeError:
        pass
    if self._is_truthy(untranslated):
```

etc.

**Comment by beniwohli** [comment]
I'm not sure what's going on here. `obj` should not be `None` (it's the value passed in in your template where you iterate over the result set from haystack). The only way I could reproduce this was by manually appending `None` to the result set I get from the `SearchView`.

But you got a point in that exceptions in the templatetag should be silenced when `settings.TEMPLATE_DEBUG != True`. Commit coming up.

**Comment by beniwohli** [comment]
@sn-devdev: feel free to reopen if this is not solving your issue.
